// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT2Eue9a32m5EPOQpDVwS0pxwco1DQGlo',
    appId: '1:403939764238:web:5ef00057a3dc8f8253345f',
    messagingSenderId: '403939764238',
    projectId: 'my-blood-donation-app1',
    authDomain: 'my-blood-donation-app1.firebaseapp.com',
    storageBucket: 'my-blood-donation-app1.appspot.com',
    measurementId: 'G-DYZ239DWSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiLCBHCp0G_UfivLOFSnN9--hcwNLnATc',
    appId: '1:403939764238:android:106da8c2aff30cd753345f',
    messagingSenderId: '403939764238',
    projectId: 'my-blood-donation-app1',
    storageBucket: 'my-blood-donation-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZhvmQtRRIem-37oCOL_qSlYx3xkAcPoI',
    appId: '1:403939764238:ios:1b1a2a390914ca2c53345f',
    messagingSenderId: '403939764238',
    projectId: 'my-blood-donation-app1',
    storageBucket: 'my-blood-donation-app1.appspot.com',
    androidClientId: '403939764238-he4n5va7lmk5kj052nd7bd6ok8bh51r3.apps.googleusercontent.com',
    iosClientId: '403939764238-2cl6ocs4vbpra6hr09j3ss5s3ugokan6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZhvmQtRRIem-37oCOL_qSlYx3xkAcPoI',
    appId: '1:403939764238:ios:1b1a2a390914ca2c53345f',
    messagingSenderId: '403939764238',
    projectId: 'my-blood-donation-app1',
    storageBucket: 'my-blood-donation-app1.appspot.com',
    androidClientId: '403939764238-he4n5va7lmk5kj052nd7bd6ok8bh51r3.apps.googleusercontent.com',
    iosClientId: '403939764238-2cl6ocs4vbpra6hr09j3ss5s3ugokan6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );
}
